---
title: "Portfolio v1"
output: 
    flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: scroll
        storyboard: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Including Plots

You can also embed plots, for example:

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(spotifyr)
library(remotes)
library(usethis)
library(ggplot2)

wave1 <- get_playlist_audio_features("", "1rcC4T1SuhqqTLw2j5KBEI")
wave2 <- get_playlist_audio_features("", "0x1XvxGALr0yY7lKos4Kg2")
wave3 <- get_playlist_audio_features("", "0k613TUDZYkomz97xX9DeZ")
wave4 <- get_playlist_audio_features("", "3Mck3Ipp6wNmmRgDfYkRza")

## remove day and month from date, just year remains

# make sure the date is indeed a date
# wave1$track.album.release_date <- as.Date(wave1$track.album.release_date)
# wave2$track.album.release_date <- as.Date(wave2$track.album.release_date)
# wave3$track.album.release_date <- as.Date(wave3$track.album.release_date)
# wave4$track.album.release_date <- as.Date(wave4$track.album.release_date)

# add column with release year of track
wave1$release_year <- c(1992, 1992, 1983, 1994, 1985, 1985, 1987, 1987, 1995, 1990, 1991, 1991)
wave2$release_year <- c(1994, 1994, 1994, 1998, 1998, 1996, 1999, 1999, 1999, 1998, 1998, 1996, 1997, 1997, 1997, 1997, 1997, 1998, 1997, 1999, 1999, 1999, 1999, 1999, 2000, 2003, 2000, 2000, 1998, 2002, 2000, 1999, 1997, 1997, 1997, 2000, 2000, 1995)
wave3$release_year <- c(1999, 2001, 2001, 2006, 2003, 2003, 2001, 2003, 2002, 2010, 2002, 2002, 2004, 2005, 2001, 2001, 1999, 1999, 2000, 2000, 2005, 2004, 2003, 2001, 2004, 2005, 2005, 2003, 2000, 2004, 2003, 2017, 2008)
wave4$release_year <- c(2014, 2014, 2010, 2018, 2018, 2017, 2017, 2017, 2010, 2015, 2018, 2016, 2014, 2016, 2017, 2018, 2014, 2013, 2013, 2013, 2014, 2012, 2013, 2018 ,2011, 2013, 2012, 2012, 2013, 2018, 2015, 2013, 2016, 2018, 2013, 2015, 2018, 2017, 2014)

# add column with number of wave
wave1$wave <- "wave1"
wave2$wave <- "wave2"
wave3$wave <- "wave3"
wave4$wave <- "wave4"

# combine data sets 'wave1', 'wave2', 'wave3', 'wave4'.
wave1234 <- rbind(wave1, wave2, wave3, wave4)

# give column names of 'wave1234', to inspect which are unnecessary and can be removed
names(wave1234)

# remove useless columns
wave1234subset <- wave1234
wave1234subset[ ,c(1,2,3,4,5,20,21,22,23,24,25,26,27,30,32,35,39,41,43,51,52,53,58)] <- list(NULL)


# continue with this, make it more informative and prettier
# ggplot(wave1234subset, aes(x = wave, y = loudness)) + 
#    geom_bar(stat = "summary", fun.y = "mean")

#mean(wave1$loudness)
#mean(wave2$loudness)
#mean(wave3$loudness)
#mean(wave4$loudness)


wave1234subset %>%
    group_by(wave) %>%
    summarise_all(mean) -> wave1234subset.summary
#wave1234subset.summary # Summary statistics


# a nice scatterplot of release year X loudness, per wave
ggplot(wave1234subset, aes(x = release_year, y = loudness, color = wave)) + 
    geom_point(stat = "summary", position = "jitter", alpha=0.7) +
    scale_x_continuous("Release year", 
                       limits = c(1980, 2020)) +
    scale_y_continuous("Loudness") +
    scale_color_discrete("wave") +
    geom_point(data = wave1234subset.summary, shape = 15, size = 5)
```
